# ==========================================
# 攻擊方陣營
# ==========================================
[Attacker]
kali_2026_01 ansible_host=10.0.0.231 ansible_user=kali ansible_become_password=kali
[Ansible_Control]
ansible_control ansible_host=10.0.0.232
# ==========================================
# 靶機陣營 (依賴作業系統分類)
# ==========================================
[Ubuntu]
ubuntu20 ansible_host=10.0.0.235
ubuntu22 ansible_host=10.0.0.236
ubuntu24 ansible_host=10.0.0.237

[bWAPP]
ubuntu12 ansible_host=10.0.0.240 ansible_ssh_common_args='-o PubkeyAcceptedKeyTypes=+ssh-rsa' ansible_python_interpreter=/usr/bin/python
ubuntu14 ansible_host=10.0.0.241 ansible_ssh_common_args='-o PubkeyAcceptedKeyTypes=+ssh-rsa' ansible_python_interpreter=/usr/bin/python

[Redhat]
centos9 ansible_host=10.0.0.233
rocky9 ansible_host=10.0.0.234


[Windows_Standalone]
win10_alone ansible_host=10.0.0.238
win11_alone ansible_host=10.0.0.239

[Windows_AD]
win2022_dc ansible_host=10.0.0.201
win2022_srv1 ansible_host=10.0.0.202
win2022_srv2 ansible_host=10.0.0.203
win10_dc_client ansible_host=10.0.0.210
win11_dc_client ansible_host=10.0.0.211

# ==========================================
# 💡 進階技巧：群組的群組 (Children)
# ==========================================
# 你原本寫了 [Victim]，但在 Ansible 裡，最優雅的做法是
# 讓 Victim 成為一個「父群組」，自動包含底下的子群組。
[Victim:children]
Ubuntu
Redhat
Windows_Standalone

# (可選) 如果你想把所有 Linux 靶機獨立成一個群組，方便派發 SSH 任務：
[Linux_Targets:children]
Ubuntu
Redhat

# ==========================================
# Windows 群組專用連線變數
# ==========================================
[Windows:children]
Windows_Standalone
Windows_AD

[Windows:vars]
# Vagrant 預設的 Windows 帳密
ansible_user=vagrant
ansible_password=vagrant
# 指定使用 WinRM 協定
ansible_connection=winrm
# 忽略自簽憑證檢查
ansible_winrm_server_cert_validation=ignore
# 傳輸驗證方式 (Vagrant Windows 通常支援 basic 或 ntlm)
ansible_winrm_transport=ntlm
ansible_port=5985
ansible_winrm_scheme=http
# 告訴 Ansible 遇到 Windows 時，不要用 sudo，改用 runas
ansible_become_method=runas
ansible_become_user=SYSTEM
# (你的 inventory.ini 原本的內容...)

# ==========================================
# 實驗室全域網路變數 (Global Variables)
# ==========================================
[all:vars]
lab_gateway="10.0.0.1"
lab_dns="1.1.1.1"
