# ==========================================
# 攻擊方陣營
# ==========================================
[Attacker]
kali_2026_01 ansible_host=10.0.0.37 ansible_user=kali

# ==========================================
# 靶機陣營 (依賴作業系統分類)
# ==========================================
[Ubuntu]
ubuntu20 ansible_host=10.0.0.41
ubuntu22 ansible_host=10.0.0.42
ubuntu24 ansible_host=10.0.0.40

[bWAPP]
ubuntu12 ansible_host=10.0.0.46 ansible_ssh_common_args='-o PubkeyAcceptedKeyTypes=+ssh-rsa' ansible_python_interpreter=/usr/bin/python
ubuntu14 ansible_host=10.0.0.47 ansible_ssh_common_args='-o PubkeyAcceptedKeyTypes=+ssh-rsa' ansible_python_interpreter=/usr/bin/python

[Redhat]
centos9 ansible_host=10.0.0.39
rocky9 ansible_host=10.0.0.43

[Windows]
#win10 ansible_host=10.0.0.x
#win11 ansible_host=10.0.0.x
#win2022 ansible_host=10.0.0.x

# ==========================================
# 💡 進階技巧：群組的群組 (Children)
# ==========================================
# 你原本寫了 [Victim]，但在 Ansible 裡，最優雅的做法是
# 讓 Victim 成為一個「父群組」，自動包含底下的子群組。
[Victim:children]
Ubuntu
Redhat
Windows

# (可選) 如果你想把所有 Linux 靶機獨立成一個群組，方便派發 SSH 任務：
[Linux_Targets:children]
Ubuntu
Redhat
